SHELL := /usr/bin/env bash
.SHELLFLAGS := -eu -o pipefail -c

CHAIN_DIR=chain
SC_DIR=smart-contracts
FE_DIR=frontend

RPC_URL=http://127.0.0.1:8545
CHAIN_ID=1515

# File address generated by chain/Makefile
VALIDATOR_FILE=$(CHAIN_DIR)/.validator
RELAYER_FILE=$(CHAIN_DIR)/.relayer

.PHONY: all
all: reset bootstrap

.PHONY: bootstrap
bootstrap: chain-up sc-deploy fe-db-up fe-migrate fe-seed
	@echo ""
	@echo "✅ ALL DONE"
	@echo "RPC       : $(RPC_URL)"
	@echo "Validator : $$(cat $(VALIDATOR_FILE) 2>/dev/null || echo 'N/A')"
	@echo "Relayer   : $$(cat $(RELAYER_FILE) 2>/dev/null || echo 'N/A')"

.PHONY: reset
reset: chain-reset fe-db-down
	@echo "✅ Reset done."

.PHONY: stop
stop:
	@echo ">> Stopping Geth and Postgres (keeping data)..."
	@$(MAKE) -C $(CHAIN_DIR) down
	@cd $(FE_DIR) && docker compose down
	@echo "✅ Stopped."

# -----------------------
# Chain
# -----------------------
.PHONY: chain-reset
chain-reset:
	@echo ">> [chain] reset"
	@$(MAKE) -C $(CHAIN_DIR) reset || true

.PHONY: chain-up
chain-up:
	@echo ">> [chain] all (reset+init+up)"
	@$(MAKE) -C $(CHAIN_DIR) all
	@echo ">> [chain] wait RPC"
	@for i in {1..40}; do \
	  curl -s -X POST $(RPC_URL) -H "Content-Type: application/json" \
	    --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":1}' >/dev/null && break; \
	  sleep 1; \
	done
	@test -f $(VALIDATOR_FILE) || (echo "❌ Missing $(VALIDATOR_FILE). Verify chain/Makefile writes .validator" && exit 1)
	@test -f $(RELAYER_FILE) || (echo "❌ Missing $(RELAYER_FILE). Verify chain/Makefile writes .relayer" && exit 1)
	@echo "   validator=$$(cat $(VALIDATOR_FILE))"
	@echo "   relayer  =$$(cat $(RELAYER_FILE))"

# -----------------------
# Smart contracts (Hardhat)
# -----------------------
.PHONY: sc-install
sc-install:
	@echo ">> [smart-contracts] npm install"
	@cd $(SC_DIR) && npm ci

.PHONY: sc-deploy
sc-deploy: sc-install
	@echo ">> [smart-contracts] deploy to geth"
	@cd $(SC_DIR) && RPC_URL="$(RPC_URL)" CHAIN_ID="$(CHAIN_ID)" npm run deploy:local

# -----------------------
# Frontend DB (postgres + prisma)
# -----------------------
.PHONY: fe-db-up
fe-db-up:
	@echo ">> [frontend] start postgres"
	@cd $(FE_DIR) && docker compose up -d

.PHONY: fe-db-down
fe-db-down:
	@echo ">> [frontend] stop postgres"
	@cd $(FE_DIR) && (docker compose down -v || true)

.PHONY: fe-install
fe-install:
	@echo ">> [frontend] npm install"
	@cd $(FE_DIR) && npm ci

.PHONY: fe-migrate
fe-migrate: fe-install
	@echo ">> [frontend] prisma db push"
	@cd $(FE_DIR) && npx prisma db push

.PHONY: fe-seed
fe-seed: fe-install
	@echo ">> [frontend] prisma seed (also grants SC roles)"
	@VALIDATOR=$$(cat $(VALIDATOR_FILE)); RELAYER=$$(cat $(RELAYER_FILE)); \
	  cd $(FE_DIR) && \
	  VALIDATOR="$$VALIDATOR" RELAYER="$$RELAYER" \
	  RPC_URL="$(RPC_URL)" \
	  npx prisma db seed
