SHELL := /usr/bin/env bash
.SHELLFLAGS := -eu -o pipefail -c

CHAIN_DIR=chain
SC_DIR=smart-contracts
FE_DIR=frontend

RPC_URL=http://127.0.0.1:8545
CHAIN_ID := 1515

# File address generated by chain/Makefile
VALIDATOR_FILE=$(CHAIN_DIR)/.validator
RELAYER_FILE=$(CHAIN_DIR)/.relayer

.PHONY: all
all: reset bootstrap

.PHONY: bootstrap
bootstrap: chain-up sc-deploy fe-db-up fe-migrate fe-seed
	@echo ""
	@echo "✅ ALL DONE"
	@echo "RPC       : $(RPC_URL)"
	@echo "Validator : $$(cat $(VALIDATOR_FILE) 2>/dev/null || echo 'N/A')"
	@echo "Relayer   : $$(cat $(RELAYER_FILE) 2>/dev/null || echo 'N/A')"

.PHONY: reset
reset: chain-reset
	@echo ">> [root] Stopping and removing volumes (Frontend/Oracle/Postgres)..."
	@docker compose down -v
	@echo "✅ Reset done (All data wiped)."

.PHONY: stop
stop:
	@echo ">> Stopping Services..."
	@$(MAKE) -C $(CHAIN_DIR) down
	@docker compose down
	@echo "✅ Stopped."

# -----------------------
# Chain
# -----------------------
.PHONY: chain-reset
chain-reset:
	@echo ">> [chain] reset"
	@$(MAKE) -C $(CHAIN_DIR) reset || true

.PHONY: chain-up
chain-up:
	@echo ">> [chain] all (reset+init+up)"
	@$(MAKE) -C $(CHAIN_DIR) all
	@echo ">> [chain] wait RPC"
	@python chain/wait_for_rpc.py $(RPC_URL)
	@cd $(CHAIN_DIR) && python init_chain.py show-info
# -----------------------
# Smart contracts (Hardhat)
# -----------------------
.PHONY: sc-install
sc-install:
	@echo ">> [smart-contracts] pnpm install"
	@cd $(SC_DIR) && pnpm install

.PHONY: sc-deploy
sc-deploy: sc-install
	@echo ">> [smart-contracts] deploy to geth"
	@cd $(SC_DIR) && python scripts/run_deploy.py

.PHONY: sc-fund-users
sc-fund-users:
	@echo ">> [smart-contracts] funding regulator & company accounts"
	@cd $(SC_DIR) && npx hardhat run scripts/fund-users.js --network localhost

# -----------------------
# Frontend DB (postgres + prisma)
# -----------------------
.PHONY: fe-db-up
fe-db-up:
	@echo ">> [frontend] start postgres (root compose)"
	@docker compose up -d postgres

.PHONY: fe-db-down
fe-db-down:
	@echo ">> [frontend] stop postgres"
	@docker compose down

.PHONY: fe-install
fe-install:
	@echo ">> [frontend] pnpm install"
	@cd $(FE_DIR) && pnpm install

.PHONY: fe-migrate
fe-migrate: fe-install
	@echo ">> [frontend] prisma db push"
	@cd $(FE_DIR) && pnpm exec prisma db push --accept-data-loss

.PHONY: fe-seed
fe-seed: fe-install
	@echo ">> [frontend] prisma seed (also grants SC roles)"
	@python chain/run_seed.py

# -----------------------
# Full Stack Run
# -----------------------
.PHONY: run
run: bootstrap
	@echo ">> Starting Services (Postgres & Chain running in Docker)..."
	@echo ">> Launching Frontend and Oracle locally..."
	@npx concurrently -k \
		"cd oracle-service && pnpm run start" \
		"cd frontend && pnpm run dev"
